-- ============================================
-- Tabela: FUNCIONARIO
-- Responsável: Rafael
-- Depende de: PESSOA (e autorrelacionamento com FUNCIONARIO)
-- ============================================
